### ISSUE TITLE
Add Go releaser workflow to simplify release process

### ISSUE THREAD

**Issue by TomChv** [PtitLuca/go-dispatcher#13]
## Context

Currently, release are made manually using `git tag` command.

I think implementing a more elaborate way can be useful for future release.

## Proposal

[Go Release](https://goreleaser.com) is a well known tool that work out of the box.
Since it has an easy [GitHub Action integration](https://goreleaser.com/ci/actions/), it doesn't cost anything to add it.

What's your opinion @PtitLuca?

**Comment by PtitLuca** [comment]
Feel free to add it ! I think it could be a nice improvement for the project 🚀

**Comment by TomChv** [comment]
Solved by #15
